= AsciiDoc support for Middleman 4
Dan Allen <https://github.com/mojavelinux[@mojavelinux]>
// Settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:note-caption: :paperclip:
endif::[]
// URIs:
:uri-repo: https://github.com/middleman/middleman-asciidoc
:uri-middleman: https://middlemanapp.com
:uri-asciidoc: http://asciidoc.org
:uri-asciidoctor: http://asciidoctor.org
:uri-gem: https://rubygems.org/gems/middleman-asciidoc
:badge-gem: https://badge.fury.io/rb/middleman-asciidoc.png
:uri-buildstatus: http://travis-ci.org/middleman/middleman-asciidoc
:badge-buildstatus: https://travis-ci.org/middleman/middleman-asciidoc.png
:uri-depstatus: https://gemnasium.com/middleman/middleman-asciidoc
:badge-depstatus: https://gemnasium.com/middleman/middleman-asciidoc.png?travis
:uri-codequality: https://codeclimate.com/github/middleman/middleman-asciidoc
:badge-codequality: https://codeclimate.com/github/middleman/middleman-asciidoc.png

Middleman AsciiDoc (gem: `middleman-asciidoc`) is an extension for the {uri-middleman}[Middleman] static site generator that adds support for the {uri-asciidoc}[AsciiDoc] markup language using {uri-asciidoctor}[Asciidoctor].

NOTE: This extension is designed for Middleman >= 4.0.0.
Prior to Middleman 4, AsciiDoc support was provided by Middleman out of the box.

ifdef::status[]
image:{badge-gem}[Gem Version,link={uri-gem}]
image:{badge-buildstatus}[Build Status,link={uri-buildstatus}]
image:{badge-depstatus}[Dependency Status,link={badge-depstatus}]
//image:{badge-codequality}[Code Quality,link={badge-codequality}]
endif::[]

== Installation

If you're just getting started, install the Middleman gem:

 $ NOKOGIRI_USE_SYSTEM_LIBRARIES=1 gem install middleman

then generate a new project:

 $ middleman init MY_PROJECT

If you're working with an existing project, you can skip the previous steps.

Finally, add `gem 'middleman-asciidoc'` to your [path]_Gemfile_ and run `bundle`.

NOTE: Each AsciiDoc file in the source directory (except files that begin with `_` or are in a directory that begins with `_`) becomes a page in the site.
AsciiDoc files can have the file extension `.adoc` or `.html.adoc`.
These extensions are stripped and replaced with the value of the `outfilesuffix` attribute, which defaults to `.html`.
(For details, see the discussion in https://github.com/middleman/middleman-asciidoc/issues/7[issue #7]).

== Configuration

```ruby
activate :asciidoc
```

You can also pass AsciiDoc configuration options to the underlying Asciidoctor processor:

```ruby
activate :asciidoc, :asciidoc_attributes => %w(foo=bar)
```

The full set of options can be seen on your preview server's config page at [path]_/__middleman/config/_.

== Community

The official community forum for Middleman can be found at http://forum.middlemanapp.com.
For questions related to this extension or general questions about AsciiDoc, please post to the Asciidoctor discussion list at http://discuss.asciidoctor.org.

== Bug reports

Github Issues are used for managing bug reports and feature requests.
If you run into issues, please search the issues and submit new problems at https://github.com/middleman/middleman-asciidoc/issues.

The best way to get quick responses to your issues and swift fixes to your bugs is to submit detailed bug reports, include test cases and respond to developer questions in a timely manner.
Even better, if you know Ruby, you can submit https://help.github.com/articles/using-pull-requests[Pull Requests] containing Cucumber Features which describe how your feature should work or exploit the bug you are submitting.

== How to run Cucumber tests

. Clone the repository:

 $ git clone https://github.com/middleman/middleman-asciidoc.git

. Install Bundler (if not already installed):

 $ gem install bundler

. Run Bundler inside the project root to install the gem dependencies:

 $ bundle

. Run test cases (based on Cucumber) using Rake:

 $ rake cucumber

== Copyright

Copyright (C) 2014-2016 Dan Allen.
Free use of this software is granted under the terms of the MIT License.
For the full text of the license, see the <<LICENSE.adoc#,LICENSE>> file.
