= AsciiDoc Extension for Middleman (powered by Asciidoctor)
Dan Allen <https://github.com/mojavelinux[@mojavelinux]>
// Settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: preamble
:toclevels: 1
endif::[]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:!toc-title:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// URIs:
:uri-repo: https://github.com/middleman/middleman-asciidoc
:uri-middleman: https://middlemanapp.com
:uri-asciidoc: http://asciidoc.org
:uri-asciidoctor: http://asciidoctor.org
:uri-gem: https://rubygems.org/gems/middleman-asciidoc
:badge-gem: https://img.shields.io/gem/v/middleman-asciidoc.svg?label=gem
:uri-build: http://travis-ci.org/middleman/middleman-asciidoc
:badge-build: https://img.shields.io/travis/middleman/middleman-asciidoc/master.svg
:uri-deps: https://gemnasium.com/middleman/middleman-asciidoc
:badge-deps: https://img.shields.io/gemnasium/middleman/middleman-asciidoc.svg
//:uri-codequality: https://codeclimate.com/github/middleman/middleman-asciidoc
//:badge-codequality: https://codeclimate.com/github/middleman/middleman-asciidoc.png

ifdef::status[]
image:{badge-gem}[Gem Version Badge,link={uri-gem}]
image:{badge-build}[Build Status Badge,link={uri-build}]
image:{badge-deps}[Dependency Status Badge,link={uri-deps}]
//image:{badge-codequality}[Code Quality Badge,link={uri-codequality}]
endif::[]

Middleman AsciiDoc (gem: *middleman-asciidoc*) is an extension for the {uri-middleman}[Middleman] static site generator that adds support for the {uri-asciidoc}[AsciiDoc] lightweight markup language.
Specifically, this extension converts AsciiDoc files in your site source to HTML pages.
This conversion is performed using {uri-asciidoctor}[Asciidoctor] by default.

IMPORTANT: This extension is designed for Middleman >= 4.0.0.
Prior to Middleman 4, AsciiDoc support was part of Middleman core.

== Installation

If you're just getting started, install the Middleman gem:

 $ NOKOGIRI_USE_SYSTEM_LIBRARIES=1 gem install middleman

then generate a new project:

 $ middleman init MY_PROJECT

If you're working with an existing project, you can skip the previous steps.

Next, add the gem for this extension to your project's [.path]_Gemfile_.

```ruby
gem 'middleman-asciidoc'
```

Finally, run Bundler using the `bundle` command:

 $ bundle

You're now ready to activate this extension and begin putting it to work.

== Activation and Configuration

```ruby
activate :asciidoc
```

You can also pass AsciiDoc configuration options to the underlying Asciidoctor processor:

```ruby
activate :asciidoc, attributes: ['source-highlighter=coderay']
```

The following option keys from the Asciidoctor API can be added to the Hash of the second argument to `activate`:

attributes (type: Hash or Array, default: [])::
Custom AsciiDoc attributes to pass to the processor.
The following implicit attributes are automatically appended to this collection.

* env=site
* env-site
* site-gen=middleman
* site-gen-middleman
* builder=middleman
* builder-middleman
* middleman-version=(value of `Middleman::VERSION` constant)
* imagesdir=(value of http_prefix + images_dir in app config)@
  - skipped if `!imagesdir` is defined as a custom attribute
  - can be overridden in page (hence the trailing @)

backend (type: Symbol, default: :html5)::
The moniker for a converter, which determines the output format to generate.

base_dir (type: String, default: nil)::
The base directory to use for the current AsciiDoc document; if not specified, defaults to the document directory (i.e., docdir).
To set the base directory to the source directory, use the value `app.source_dir.expand_path`.

safe (type: Symbol, default: :safe)::
The safe mode level under which to run the AsciiDoc processor.

TIP: The full set of options can be seen on your preview server's config page at the path [.path]_/__middleman/config/_.

== Creating Pages

Each AsciiDoc file in the source directory (except for files that begin with `+_+` or which are located in a directory that begins with `+_+`) becomes a page in the site.
AsciiDoc files can have the file extension `.adoc` or `.html.adoc`.
These extensions are stripped and replaced with the value of the `outfilesuffix` attribute, which defaults to `.html`.

NOTE: For details about how the file extension is substituted, see the discussion in https://github.com/middleman/middleman-asciidoc/issues/7[issue #7].

To add a page composed in AsciiDoc, simply add an AsciiDoc file that has one of the aforementioned AsciiDoc file extensions to the project source directory.

.sample.adoc
[listing]
....
= Sample Page
:page-layout: page
:uri-asciidoctor: http://asciidoctor.org

This is a sample page composed in AsciiDoc.
The Middleman AsciiDoc extension converts it to HTML using {uri-asciidoctor}[Asciidoctor].

[source,ruby]
----
puts "Hello, World!"
----
....

=== Adding Custom Page Data

AsciiDoc attributes defined in the document header whose names begin with `page-` are promoted to page data (aka front matter).
The part of the name after the `page-` prefix is used as the entry's key (e.g., page-layout becomes layout).
The value is parsed as https://en.wikipedia.org/wiki/YAML[YAML] data (that which can be expressed in a single line).

In addition to these explicit page attributes, the following AsciiDoc attributes are also promoted to page data:

* doctitle (i.e., the document title) (becomes title)
* author
* email
* revdate (becomes date; value is converted to a DateTime object)

TIP: You can continue to specify page data using the front matter header.
The AsciiDoc `page-` attributes override matching entries in the front matter header.

=== Specifying a Layout

The most important of these page attributes is `page-layout`, which determines the layout that is applied to the page.
Middleman will look for the first file that matches this root name under the source directory and use it as the layout.
For example, if `page-layout` has the value `page`, Middleman might resolve a layout named [.path]_page.erb_.
You can fix the extension of the layout file using the `page-layout-engine` attribute.

If a layout is not specified, or the value of the `page-layout` attribute is empty, the default layout for the site is used.

If the `page-layout` attribute is unset, the AsciiDoc processor will generated a standalone document (`header_footer: true`).
In this case, the page will appear like an HTML file that is generated by the AsciiDoc processor directly.

To review, here are the different ways to specify a layout:

* `:page-layout: default` -- use the page layout named "`default`" (e.g., [.path]_default.erb_)
* `:!page-layout:` -- no layout; generate a standalone HTML document
* `:page-layout:` -- use the auto-detected layout
* _(not specified)_ -- use the auto-detected layout

.Layout for blog posts
WARNING: If you're using the Middleman Blog extension to write blog posts, you *must* specify the page layout using the `page-layout` attribute for each post written in AsciiDoc.
Otherwise, an exception will be thrown.
This requirement will be lifted once the fix for https://github.com/middleman/middleman-blog/issues/296[issue middleman-blog#296] makes it into a release.

=== Ignoring a Page

In addition to the normal ignore filter in Middleman, you can also control whether a page is ignored from AsciiDoc.
To mark a page as ignored from AsciiDoc, set the `page-ignored` attribute in the AsciiDoc document header to any value other than `false`, as follows:

----
= Ignored Page
:page-ignored:
----

Once this page attribute is detected, no further processing is performed on the document by this extension.

=== Marking an Article as a Draft

If you're using the Middleman Blog extension, you can mark an article as a draft so it does not get published.
To do so, assign the value `false` the page attribute named `page-published` in the AsciiDoc document header, as follows:

----
= Draft Article
:page-published: false
----

This effectively sets the `published` key in the page data to `false`.
Recall that the AsciiDoc extension converts the value of page attributes as a YAML value, which means the string literal "`false`" becomes the boolean value `false`.
Middleman then knows not to publish this article.

Another option is to set the date of the article way into the future.

----
= Future Post
Author Name
3001-01-01
----

By default, the blog extension does not publish articles with a future date.

=== Linking Between Pages

You can link from one page to another using an {uri-asciidoctor}/docs/user-manual/#inter-document-cross-references[inter-document xref].
Let's say you have the following two pages in the source directory:

* about.adoc
* team.adoc

You can link from the about page to the team page using the following:

----
Meet our <<team.adoc#,team>>.
----

The `.adoc#` suffix indicates the xref targets another page.
The target is the path from the current page to the other page (a source-to-source reference).
This reference is then converted to the following HTML:

[source,html]
----
Meet our <a href="team.html">team</a>.
----

Of course, we're assuming there that the input maps 1-to-1 to the output.
That assumption breaks down as soon as you enable directory indexes.

When directory indexes are enabled, each page is moved into its own folder and renamed to index.html.
So how does the xref work in that case?

This extension provides built-in support for directory indexes.
When the directory indexes extension is enabled, this extension automatically defines the `relfileprefix` and `relfilesuffix` attributes on the AsciiDoc document.
The `relfilesuffix` attribute honors both the `:trailing_slash` and `:strip_index_file` options in Middleman.
However, you have to make one change to your pages for these attributes to work with the xref macro.

Below the document header (but *not in* the document header), you must assign the `outfilesuffix` attribute to the value of the `relfilesuffix` attribute.
Here's an example:

----
= About Us

// ^ the previous blank line is required!
\ifdef::relfilesuffix[:outfilesuffix: {relfilesuffix}]

...

Meet our <<team.adoc#,team>>.
----

With the help of the `outfilesuffix` assignment, Asciidoctor automatically produces the correct link to the other page.

[source,html]
----
Meet our <a href="../team/">team</a>.
----

Optionally, you can construct the link manually using:

----
Meet our link:{relfileprefix}team{relfilesuffix}[team].
----

I think you'll agree that using the xref macro is simpler.

== Building Your Site

You can now build your site using:

 $ middleman build

or preview it using:

 $ middleman serve

If you're using Bundler, use the following commands instead:

 $ bundle exec middleman build
 $ bundle exec middleman serve

== Community

The official community forum for Middleman can be found at http://forum.middlemanapp.com.
For questions related to this extension or general questions about AsciiDoc, please post to the Asciidoctor discussion list at http://discuss.asciidoctor.org.

== Bug Reports

Github Issues are used for managing bug reports and feature requests.
If you run into issues, please search the issues and submit new problems in the project's https://github.com/middleman/middleman-asciidoc/issues[issue tracker].

The best way to get quick responses to your issues and swift fixes to your bugs is to submit detailed bug reports, include test cases and respond to developer questions in a timely manner.
Even better, if you know Ruby, you can submit https://help.github.com/articles/using-pull-requests[pull requests] containing Cucumber Features which describe how your feature should work or exploit the bug you are submitting.

== How to Run Tests

The tests are based on Cucumber.
Here's how to clone the project and run the tests.

. Clone the repository:

 $ git clone https://github.com/middleman/middleman-asciidoc.git &&
   cd middleman-asciidoc

. Install Bundler (if not already installed):

 $ gem install bundler

. Run Bundler (from the project root) to install the gem dependencies:

 $ bundle

. Run test cases (based on Cucumber) using Rake:

 $ bundle exec rake cucumber

== Copyright

Copyright (C) 2014-2016 Dan Allen and the Asciidoctor Project.
Free use of this software is granted under the terms of the MIT License.
For the full text of the license, see the <<LICENSE.adoc#,LICENSE>> file.
