name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  - cron: '45 2 * * MON'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ['2.7', '3.2']
        exclude:
        - os: ubuntu-latest
          ruby: '3.2'
        include:
        #- os: windows-latest
        #  ruby: '3.2'
        - os: macos-latest
          ruby: '3.2'
        - os: ubuntu-latest
          ruby: '3.2'
          primary: primary
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Configure Bundler
      run: bundle config --local path .bundle/gems
    - name: Install system dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libxslt1-dev
    - name: Install dependencies
      run: bundle --jobs 3 --retry 3
    - name: Enable coverage
      if: matrix.primary
      run: echo 'COVERAGE=true' >> $GITHUB_ENV
    - name: Run tests
      run: bundle exec ruby -w $(bundle exec ruby -e 'print File.join Gem.bindir, %q(rake)') cucumber
      env:
        TEST: 'true'
