name: Release
on:
  push:
    tags: ['v*']
jobs:
  activate:
    if: github.repository == 'middleman/middleman-asciidoc'
    runs-on: ubuntu-latest
    steps:
    - run: echo ok go
  build:
    needs: activate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Configure Bundler
      run: bundle config --local path .bundle/gems
    - name: Install dependencies
      run: bundle --jobs 3 --retry 3
    - name: Run tests
      run: TEST=true bundle exec rake cucumber
    - name: Publish gem
      uses: dawidd6/action-publish-gem@v1
      with:
        api_key: ${{ secrets.RUBYGEMS_API_KEY }}
